#!/bin/bash
# Test extraction and re-creation of VI files
# You need a group of vi/ctl/vit/mnu files to execute this test on.
# To verify changes in pylabview code, directory 'vi.lib'
# from LV installation can be used.
set -x
#set -e

SRC_VI_DIRS='../lv025 ./lv025 ../lv06 ./lv06 ../lv07 ./lv07 ../lv10 ./lv10 ../lv14 ./lv14'
STORE_EXTRACTED_FILES=false

mkdir -p ../test_out
cd ../test_out

echo | tee log-vi_lib-vi-1extr.txt
echo | tee log-vi_lib-vi-2creat.txt
echo | tee log-vi_lib-vi-3cmp.txt


# LLB files generated by the tool are NOT the same as original on binary level. That's because names section generation has time dependencies.
# Find supported files, other than LLBs. We have a separate script for the LLBs.
find ${SRC_VI_DIRS} -type f -iname '*.vi' -o -iname '*.ctl' -o -iname '*.vit' -o -iname '*.mnu' -o -iname '*.ctt' -o -iname '*.uir' -o -iname '*.lsb' | tee log-vi_lib-vi-0list.txt

# Remove LV6 files which generate irrelevant differences due to random padding
sed -i -n '/lv06\/vi[.]lib\/\(Demo Scope\|GMath\/Conjugate Gradient nD\|GMath\/Eval X-Y-Z[\(]a,t1,t2[\)]\|GMath\/Nonlinear System Solver\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(GMath\/ODE Cash Karp 5th Order\|GMath\/ODE Runge Kutta 4th Order\|GMath\/Parse Formula Node\|GMath\/String to Tree Inner Part\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Averaged DC-RMS\|Measure\/Basic Averaged DC-RMS\|Measure\/Basic Function Generator\|Measure\/Create Continuous Mask\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Create Segmented Mask using Formula\|Measure\/Create Segmented Mask\|Measure\/Cross Spectrum [\(]Mag-Phase[\)]\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Cross Spectrum [\(]Real-Im[\)]\|Measure\/Design IIR filter\|Measure\/Design N FIR filters\|Measure\/Design N IIR filters\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Extract Single Tone Information from Hann Spectrum\|Measure\/FFT Power Spectral Density\|Measure\/FFT Power Spectrum\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/FFT Spectrum [\(]Mag-Phase[\)]\|Measure\/FFT Spectrum [\(]Real-Im[\)]\|Measure\/FIR Filter by N Specs for N Chan\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/FIR Filter for N Chan\|Measure\/Frequency Response Function [\(]Mag-Phase[\)]\|Measure\/Frequency Response Function [\(]Real-Im[\)]\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Harmonic Distortion Analyzer\|Measure\/Implement IIR Cascade Filter for N Chan\|Measure\/Implement IIR Cascade Filter for N Specs and N Chan\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/Implement IIR Direct Filter for N Chan\|Measure\/Limit Testing for Cluster\|Measure\/Limit Testing\|Measure\/ma_Compute Order [&] Cutoffs\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Measure\/ma_Design FIR Coeff\|Measure\/Multitone Generator\|Measure\/SINAD Analyzer\|Measure\/Trigger Detection for N Channel\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(picture\/Calc Axis Attributes\|picture\/Draw Axes\|picture\/Draw Cartesian Axes\|picture\/Draw Standard Smith Grid\|picture\/Draw XY Data\|picture\/Plot XY\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(platform\/Compile DLL Stub\|platform\/DataSocket Status\|platform\/Notifier Core\|platform\/Wait On ActiveX Event From Multiple\|registry\/Create Registry Key\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(registry\/Enum Registry Values\|registry\/Open Registry Key\|registry\/Read Registry Value STR\|sound\/Snd Write Wave File\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(utility\/All Librarian VIs\|utility\/All the eggs\|utility\/Append Control Image to Report\|utility\/Append Front Panel Image to Report\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(utility\/Append List to Report\|utility\/Append Text Table to Report\|utility\/Config Data Modify\|utility\/Config Data Registry\|utility\/Easy Text Report\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(utility\/General Error Handler\|utility\/HTML Report Labeled Numeric Table\|utility\/HTML Report Labeled String Table\|utility\/Image in Header or Footer\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(utility\/Instrument Control Master\|utility\/Open-Create-Replace File\|utility\/Print By Name Master\|utility\/threadconfig\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(utility\/Version Control CIN\|Waveform\/Export Waveforms To Spreadsheet File [\(]1D[\)]\|Waveform\/Export Waveforms To Spreadsheet File [\(]2D[\)]\)[.]vi/!p' log-vi_lib-vi-0list.txt
sed -i -n '/lv06\/vi[.]lib\/\(Waveform\/Open Create Replace WDT Array Dlog File\|Waveform\/Read WDT Array Dlog File[\+]\|Waveform\/Search Waveform\|Waveform\/Write WDT Array Dlog File[\+]\)[.]vi/!p' log-vi_lib-vi-0list.txt
# Remove files which generate irrelevant differences due to different order inside
sed -i -n '/lv07\/user[.]lib\/\(dir\)[.]mnu/!p' log-vi_lib-vi-0list.txt

while IFS= read -r rsrc_fn; do
    rsrc_out_fn=$(basename "${rsrc_fn}")
    rsrc_dir=$(dirname "${rsrc_fn}")
    rsrc_base_fn=${rsrc_out_fn%.*}
    xml_fn="${rsrc_base_fn}.xml"
    if $STORE_EXTRACTED_FILES; then
        rsrc_out_dir=${rsrc_dir#"./"}
        rsrc_out_dir="./extract/"${rsrc_out_dir#"../"}
        mkdir -p "${rsrc_out_dir}"
    else
        rsrc_out_dir="."
    fi

    (../readRSRC.py -vv -x -i "${rsrc_fn}" -m "${rsrc_out_dir}/${xml_fn}") 2>&1 | tee -a log-vi_lib-vi-1extr.txt
    #mv "${rsrc_fn}" "${rsrc_fn}.orig"

    # Now some fixups for XML parser not meeting standards; will be fixed in Python 3.9
    if [[ "${rsrc_fn}" == *'/Equi-Ripple BandPass (CDB).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple BandPass (DBL).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple BandStop (CDB).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple BandStop (DBL).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple HighPass (CDB).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple HighPass (DBL).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple LowPass (CDB).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple LowPass (DBL).vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple BandPass PtByPt.vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple BandStop PtByPt.vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple HighPass PtByPt.vi' ]] || \
       [[ "${rsrc_fn}" == *'/Equi-Ripple LowPass PtByPt.vi' ]] || \
       [[ "${rsrc_fn}" == *'/Parks-McClellan.vi' ]] || \
       [[ "${rsrc_fn}" == *'/ma_sml_Compensation Filter Design.vi' ]] || \
       [[ "${rsrc_fn}" == *'/ma_Equi-RippleFIRCoeff.vi' ]] || \
       [[ "${rsrc_fn}" == *'/ma_Design FIR Coeff.vi' ]] || \
       [[ "${rsrc_fn}" == *'/ma_sml_Last Stage FIR Filter Design.vi' ]] || \
       false; then
        (echo "FIX ${rsrc_out_fn} - it contains CR which ElementTree converts to LF") 2>&1 | tee -a log-vi_lib-vi-1extr.txt
        sed -i 's/"\(Weighted\)&#10;\(Ripple\)"/"\1\&#13;\2"/' "${rsrc_out_dir}/${xml_fn}"
    elif [[ "${rsrc_fn}" == *'/Serial Port Reset.vi' ]] || \
       false; then
        (echo "FIX ${rsrc_out_fn} - it contains CR which ElementTree converts to LF") 2>&1 | tee -a log-vi_lib-vi-1extr.txt
        sed -i 's/"\(.* HShk[.]\)&#10;\([\(][A-Z]\+[\)]\)"/"\1\&#13;\2"/' "${rsrc_out_dir}/${xml_fn}"
    fi

    (../readRSRC.py -vv -c -m "${rsrc_out_dir}/${xml_fn}" -i "${rsrc_out_fn}") 2>&1 | tee -a log-vi_lib-vi-2creat.txt
    if [[ "${rsrc_fn}" == *'/FFT Power Spectrum.vi' ]] || \
       false; then
        # For some specific files, ignore EOLN conversion inconsistencies
        (cmp -l "${rsrc_fn}" "${rsrc_out_fn}") 2>&1 | head -n 64 | grep -v '^[0-9]\+[ ]\+15[ ]\+12$' | tee -a log-vi_lib-vi-3cmp.txt
    else
        (cmp -l "${rsrc_fn}" "${rsrc_out_fn}") 2>&1 | head -n 64 | tee -a log-vi_lib-vi-3cmp.txt
    fi
    rsrc_base_pattern="${rsrc_base_fn}"
    rsrc_base_pattern="${rsrc_base_pattern//[/\\[}"
    rsrc_base_pattern="${rsrc_base_pattern//]/\\]}"
    if ! $STORE_EXTRACTED_FILES; then
        find "${rsrc_out_dir}/" -maxdepth 1 -type f -name "${rsrc_base_pattern}*" -exec rm {} +
    fi
done < log-vi_lib-vi-0list.txt

cd ../tests

sed -n 's/^.*\(Warning: .*\)$/\1/p' ../test_out/log-vi_lib-vi-1extr.txt | sort | uniq -c | sort > ../test_out/log-vi_lib-vi-1extr-warns.txt

if grep -q '^\(cmp:\|[ ]*[0-9]\+ \)' ../test_out/log-vi_lib-vi-1extr.txt; then
    echo Some comparisons FAILED!
else
    echo All tests ended with SUCCESS
fi

exit 0
